# Generated by Django 4.2.10 on 2024-03-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_complaint_is_anonymous_alter_complaint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='review',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('notreviewed', 'Not Reviewed'), ('in_progress', 'In Progress'), ('reviewed', 'Reviewed')], default='notreviewed', max_length=20),
        ),
    ]
