# Generated by Django 4.2.11 on 2024-03-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_thread_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='threat',
            new_name='thread',
        ),
    ]
