# Generated by Django 4.2.11 on 2024-04-09 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_complaint_review_complaint_status'),
        ('loginApp', '0004_rename_threat_post_thread'),
    ]

    operations = [
    ]
