# Generated by Django 5.0.2 on 2024-04-24 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0005_merge_20240409_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='upload',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='review',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ComplaintFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='complaint_files/%Y/%m/%d/')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='loginApp.complaint')),
            ],
        ),
    ]
